Make sure on-exit-leak-free is run on node >=14
Since it uses WeakRef and FinalizationRegistry available only from Node v14.
It would otherwise give errors like
```
ReferenceError: FinalizationRegistry is not defined
    at Object.<anonymous> (node_modules/on-exit-leak-free/index.js:11:18)
```